---
openapi: 3.0.2
info:
  title: <Your Project Name>
  description: <Your Project Description>
  version: 0.0.1
paths:
  "/hello-world":
    get:
      tags:
        - HTTP Methods
      summary: The request's GET parameters.
      operationId: get_method
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
