---
openapi: 3.1.0
info:
  title: Sample API
  version: 0.1.9
paths:
  /address:
    post:
      requestBody:
        required: true
        content:
          "*/*":
            schema:
              type:
                - string
      responses:
        default:
          description: no response
  /info:
    post:
      requestBody:
        required: true
        content:
          "*/*":
            schema:
              type:
                - string
      responses:
        default:
          description: no response
    get:
      responses:
        default:
          description: retrieve application information
